### ISSUE TITLE
View should scroll to top when paging / changing tables

### ISSUE THREAD

**Issue by JRGould** [deliciousbrains/sqlbuddy#30]
When paging or changing tables, the window doesn't scroll back to the top - so if you've got a lot of tables in a DB, selecting a new table towards the bottom of the list that only has a couple rows of data can make it seem like nothing has happened.

![jul-30-2016 10-16-11](https://cloud.githubusercontent.com/assets/1509647/17271968/cebc945e-563e-11e6-8921-222769e2b054.gif)

Additionally, table listing should probably scroll independently of the data view.

**Comment by gilbitron** [comment]
Fixed in https://github.com/deliciousbrains/sqlbuddy/commit/d94de4e929e79cc1a9a15e6dac62dce7b81996f6
