### ISSUE TITLE
Add working indicator

### ISSUE THREAD

**Issue by JRGould** [deliciousbrains/sqlbuddy#31]
When loading a new page, table, or database - there's no indication that the app is "working". On a highly responsive server, this is mostly fine, but when there's latency this can cause confusion. 

We should probably add a dark or light overlay to the page with a spinner or some working indicator when a view change is initiated, and remove it when data is loaded.

**Comment by Oxicode** [comment]
:+1:

**Comment by gilbitron** [comment]
Fixed in https://github.com/deliciousbrains/sqlbuddy/commit/1a7016562a21f1867247739b93393c4b7288cd0c
