### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [deliciousbrains/sqlbuddy#36]
As title, I want to know which branch is the current and active.

It seems that the latest commit is about three years ago in `develop` branch.

And the latest commit is about six years ago in `master` branch.

They're inactive for a while.

**Comment by am9417** [comment]
I was worried about the inactivity too when I had to update this to PHP 7 for our project. I made a pull request to master and it got accepted, so seems this isn't completely dead :)

**Comment by peter279k** [comment]
Hi @am9417, thanks for your reply.

I think I can help you to work on this if possible :).
