### ISSUE TITLE
Undefined Index at dboverview.php on line 216

### ISSUE THREAD

**Issue by KoenDG** [deliciousbrains/sqlbuddy#7]
I imported the MySQL example database "[Sakila][1]" just now. I imported it without error via the mysql shell.

When I went to check the tables in sqlbuddy(latest version, no updates available), I was presented with this error:

![Undefined Index notice][2]
I am using Ubuntu 12.10,

PHP version output:

    koen@ubuntu:~$ php -v
    PHP 5.4.12 (cli) (built: Feb 28 2013 16:43:35) 
    Copyright (c) 1997-2013 The PHP Group
    Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
        with Xdebug v2.2.2, Copyright (c) 2002-2013, by Derick Rethans

`XDebug.scream` is off.

MySQL version output:

    koen@ubuntu:~$ mysql --version
    mysql  Ver 14.14 Distrib 5.5.29, for debian-linux-gnu (x86_64) using readline 6.2

My php.ini has the default setting for error display:

    error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED

I provided a link to the Sakila database, it can be easily installed following the instructions on the mysql website. Reproducing this should require no more than simply importing the database and viewing it with sqlbuddy.

Since this is a notice, I am confused that it has been displayed. The error_reporting should turn it off and even XDebug.scream is off(which reports errors even if php.ini suppresses them).

Still, I thought I'd report it, in case someone wanted to deal with the issue.

  [1]: http://dev.mysql.com/doc/sakila/en/index.html
  [2]: http://i.imgur.com/grst16o.png

**Comment by gilbitron** [comment]
Closing this as we are planning a ground up rewrite for v2.0.
