### ISSUE TITLE
Cross-Site Scripting in 'browse.php'

### ISSUE THREAD

**Issue by omarkurt** [deliciousbrains/sqlbuddy#9]
Netsparker Found XSS in browse.php

Url:  http://example.com/sqlbuddy/browse.php?ajaxRequest=89&requestKey=be91e6d9714bb1c4&db=information_schema&table=&#39;&quot;--&gt;&lt;/style&gt;&lt;/scRipt&gt;&lt;scRipt&gt;alert(0x000290)&lt;/scRipt&gt; 
Parameter Name:  table  
Parameter Type:  Querystring  
Attack Pattern  &#39;&quot;--&gt;&lt;/style&gt;&lt;/scRipt&gt;&lt;scRipt&gt;alert(0x000290)&lt;/scRipt&gt; 

Reference:
https://www.netsparker.com/crosssite-scripting-xss/
https://www.netsparker.com/netsparker-advisories/

**Comment by gilbitron** [comment]
Closing this as we are planning a ground up rewrite for v2.0.
